apps/proj/urls.py
from django.urls import path, re_path

from . import views

from django.conf import settings
from django.conf.urls.static import static
from .views import(
    CreateHomeworkViev,
    IndexView,
    RegisterView,
    ShowView,
    LogoutView, 
    LoginView
)

urlpatterns = [
    path('',                        IndexView.as_view(),            name='page_main'),
    path('show/<int:homework_id>/', ShowView.as_view(),             name='page_show'),
    path('delete/',                 views.delete,                   name='page_delete'),
    path('register/',               RegisterView.as_view(),         name='page_register'),
    path('login/',                  LoginView.as_view(),            name='page_login'),
    path('logout/',                 LogoutView.as_view(),           name='page_logout'),
    path('create_hw/',              CreateHomeworkViev.as_view(),   name='page_create_hw'),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
 

urls/urls.py
import django
from django.contrib import admin
from django.conf import settings
from django.urls import include, path


urlpatterns = [
    path('', include('proj.urls')),
    path(settings.ADMIN_SITE_URL, admin.site.urls),
]
if settings.DEBUG:
    urlpatterns += [
        path('__debug__/', include('debug_toolbar.urls')),
    ]

apps/proj/models.py
from django.db import models

from django.db import models
from django.contrib.auth.models import User
from django.forms import ValidationError
from django.db.models import QuerySet
from django.contrib.auth.models import (AbstractBaseUser, PermissionsMixin)

from abstracts.models import AbstractDateTime
from auths.models import CustomUser


class StudentQuerySet(QuerySet): 
    ADAULT_AGE = 18 

    def get_adault_students(self)-> QuerySet:
        return self.filter(
            age__gte=self.ADAULT_AGE
        )


class AccountQuerySet(QuerySet):
    HIGH_GPA_LVL = 4.0

    def get_superusers(self)-> QuerySet:
        return self.filter(
            user__is_superuser=True
        )


class GroupQuerySet(QuerySet):
    HIGHT_GPA_LVL = 4.0

    def get_students_with_high_gpa(self) -> QuerySet:
        return self.filter(
            self.Stuent.gpa__gt == self.HIGHT_GPA_LVL
        )
    
# class HomeworkQuerySet(QuerySet):
    
#     def get_delete_homeworks(self) -> QuerySet:
#         if Homework.DateTimeDeleted == NULL:
#             return
#         else:
#             self.filter(
#                 self.Homework.not_deleted == False
#             )


class HomeworkQuerySet(QuerySet):
    
    def get_not_deleted(self) -> QuerySet:
        return self.filter(
            datetime_deleted__isnull=True
        )

# class FileQuerySet(QuerySet):
    
#     def get_is_checked_homeworks(self) -> QuerySet:
#         return self.filter(
#             homework__is_checked=True
#         )

class Group(AbstractDateTime):
    pass
    GROUP_NAME_MAX_LENGTH = 10

    name = models.CharField(
        max_length=GROUP_NAME_MAX_LENGTH
    )

    def __str__(self) -> str:
        return f'Group: {self.name}'

    class Meta:
        ordering = (
            'name',
        )
        verbose_name = 'Группа'
        verbose_name_plural = 'Группы'


class Student(AbstractDateTime):

    GROUP_NAME_MAX_LENGHT = 15
    MAX_AGE = 27

    account = models.ForeignKey(
        CustomUser,
        on_delete=models.CASCADE
    )

    age = models.IntegerField(
        'Возраст студента'
    )

    group = models.ForeignKey(
        Group,
        on_delete=models.PROTECT
    )
    gpi = models.FloatField(
        'Средний балл',

    )

    def __str__(self) -> str:
        return f'Аккаунт: {self.account} \
        Возраст {self.age} \
        Группа {self.group.name} \
        Cредний балл {self.gpi}'

    def save(
        self, 
        *args: tuple,
        **kwargs: dict
    ) -> None:
        if self.age > self.MAX_AGE:
            raise ValidationError(
                f'Максимально допустимый возраст {self.MAX_AGE}'
            )
        super().save(*args, **kwargs)

        
    objects = AccountQuerySet().as_manager()

    class Meta:
        ordering = (
            'group','age'
        )
        verbose_name = 'Студент'
        verbose_name_plural = 'Студенты'


class Professor(AbstractDateTime):

    FULL_NAME_MAX_LENGTH = 40
    TOPIC_MAX_LENGTH = 30

    TOPIC_JAVA = 'java'
    TOPIC_PYTHON = 'python'
    TOPIC_GOLANG = 'golang'
    TOPIC_TYPESCRIPT = 'typescript'
    TOPIC_SWIFT = 'swift'
    TOPIC_PHP = 'php'
    TOPIC_MATLAB = 'matlab'
    TOPIC_SQL = 'sql'
    TOPIC_RUBY = 'ruby'
    TOPIC_DELPHI = 'delphi'

    TOPIC_CHOICES = (
        (TOPIC_JAVA,'Java'),
        (TOPIC_PYTHON,'Python'),
        (TOPIC_GOLANG,'Golang'),
        (TOPIC_TYPESCRIPT,'Typescript'),
        (TOPIC_SWIFT,'Swift'),
        (TOPIC_PHP,'PHP'),
        (TOPIC_MATLAB,'MatLab'),
        (TOPIC_SQL,'SQL'),
        (TOPIC_RUBY,'Ruby'),
        (TOPIC_DELPHI,'Delphi')
    )
    full_name = models.CharField(
        verbose_name='Полное имя',
        max_length=FULL_NAME_MAX_LENGTH
    )
    topic = models.CharField(
        verbose_name='Предмет',
        choices=TOPIC_CHOICES,
        default=TOPIC_JAVA,
        max_length=TOPIC_MAX_LENGTH
    )
    students = models.ManyToManyField(
        Student
    )

    def __str__(self) -> str:
        return f'Преподаватель: {self.full_name} \
        Предмет {self.topic} \
        Студенты {self.students}'

    def save(
        self,
        *args,
        **kwargs
        ):
        super().save(*args, **kwargs)

    class Meta:
        ordering = (
            'topic',
        )
        verbose_name = 'Преподаватель'
        verbose_name_plural = 'Преподаватели'


class Homework(AbstractDateTime):

    IMAGE_TYPES = (
        'img',
        'jpeg',
        'png',
        'jpg'
    )
    
    user = models.ForeignKey(
        CustomUser, on_delete=models.PROTECT
    )
    title = models.CharField(max_length=100)

    subject = models.CharField(max_length=50)
    
    logo = models.ImageField(
        'Лого домашней работы',
        upload_to='homework/',
        max_length=255
    )
    
    objects = HomeworkQuerySet().as_manager()

    # @property
    # def is_checked(self)->bool:
    #     return f'{self.subject} | {self.title}'

    # @property
    # def is_checked(self)->bool:
    #     return File.objects.filter(homework=self).values('is_checked')

    @property
    def is_checked(self)->bool:
        return all(
            self.files.values_list(
                'is_checked', flat=True
            )
        )

    def __str__(self) -> str:
        return f'{self.subject} | {self.title}'

    class Meta:
        ordering = (
            'datetime_created',
        )
        verbose_name = 'Домашняя работа'
        verbose_name_plural = 'Домашние работы'

class File(AbstractDateTime):

    homework = models.ForeignKey(
        Homework, on_delete=models.PROTECT
    )

    title = models.CharField(max_length=100)
    
    obj = models.FileField(
        'Объект файла',
        upload_to='homework_files/%Y/%m/%d/',
        max_length=255
    )

    is_checked = models.BooleanField(default=False)

    # objects = FileQuerySet().as_manager()

    def __str__(self) -> str:
        return f'{self.homework.title} | {self.title}'

    class Meta:
        ordering = (
            '-datetime_created',
        )
        verbose_name = 'Файл'
        verbose_name_plural = 'Файлы'

apps/proj/views.py
from argparse import FileType
from email.mime import image
from resource import prlimit
from typing import Optional, Tuple
from urllib import request, response

from django.core.handlers.wsgi import WSGIRequest
from django.http import HttpResponse, QueryDict
from django.db.models import QuerySet
from django.contrib.auth.models import User
from django.shortcuts import render
from django.contrib.auth import (
    authenticate as dj_authenticate,
    login as dj_login,
    logout as dj_logout,
)
from django.template import loader
from django.views import View

from auths.forms import CustomUserForm
from auths.models import CustomUser
from abstracts.hanlers import ViewHandler
from . models import (
    File,
    Homework,
    Student
)
from proj.forms import(CreateHomeworkForm)

class IndexView(ViewHandler, View):

    template_name = 'proj/index.html'

    queryset: QuerySet = Homework.objects.filter()
    
    def get(
        self, 
        request: WSGIRequest,
        *args: tuple,
        **kwargs
        ):

        response: Optional[HttpResponse] = self.get_validated_response(
            request
        )
        if response: 
            return response

        homeworks: QuerySet = Homework.objects.filter(
            user=request.user
        )
        if not homeworks:
            homeworks = self.queryset

        context: dict = {
            'ctx_title': 'Главная',
            'ctx_homeworks': homeworks,
        }
           
        return self.get_http_response(
            request,
            self.template_name,
            context,
        )


class RegisterView(ViewHandler, View):

    template_name = 'proj/register.html'

    queryset: QuerySet = Homework.objects.filter()
    
    def get(
        self, 
        request: WSGIRequest,
        *args: tuple,
        **kwargs
        ):
        
        form: CustomUserForm = CustomUserForm(
            request.POST,
        )

        homeworks: QuerySet = Homework.objects.filter(
            user=request.user
        )

        context: dict = {
            'form': form,
        }

        template_name = 'proj/register.html'
        

        return self.get_http_response(
            request,
            self.template_name,
            context,
        )

    def post(
        self, 
        request: WSGIRequest,
        *args: tuple,
        **kwargs
        ):

        form: CustomUserForm = CustomUserForm(
            request.POST,
        )

        if form.is_valid():
            user: CustomUser = form.save(
                commit=False
            )
            email: str = form.cleaned_data['email']
            password: str = form.cleaned_data['password']
            user.email = email
            user.set_password(password)
            user.save()

            user: CustomUser = dj_authenticate(
                email=email,
                password=password
            )
            if user and user.is_active:

                dj_login(request, user)

                homeworks: QuerySet = Homework.objects.filter(
                    user=request.user
                )

                context: dict = {
                    'ctx_homeworks': homeworks,
                }   
                
                template_name = 'proj/page_main.html'

                return self.get_http_response(
                    request,
                    self.template_name,
                    context,
                )

        context: dict = {
            'form': form,
        }

        return self.get_http_response(
            request,
            self.template_name,
            context,
        )


class LoginView(ViewHandler, View):

    template_name = 'proj/show.html'

    queryset: QuerySet = Homework.objects.get_not_deleted()

    def get(
        self, 
        request: WSGIRequest,
        *args: tuple,
        **kwargs
        ):

        form: CustomUserForm = (
            request.POST
        )

        homework: QuerySet = Homework.objects.filter(
            user=request.user
        )
        
        context: dict = {
            'form': form,
        }

        template_name: str = 'proj/login.html'

        return self.get_http_response(
            request,
            template_name,
            context, 
        )

    def post(
        self, 
        request: WSGIRequest,
        *args: tuple,
        **kwargs
    ):

        email: str = request.POST['email']
        password: str = request.POST['password']

        user: CustomUser = dj_authenticate(
            email=email,
            password=password
        )

        if not user:
            return render(
                request,
                'proj/login.html',
                {'error_message': 'Невереные данные'}
            )

        if not user.is_active:
            return render(
                request,
                'proj/login.html',
                {'error_message': 'Ваш аккаунт был удален'}
            )

        dj_login(request, user)

        homeworks: QuerySet = Homework.objects.filter(
            user=request.user
        )

        context: dict = {
            'homeworks': homeworks
        }

        return self.get_http_response(
            request,
            self.template_name,
            context,
        )


class IndexView(ViewHandler, View):

    template_name = 'proj/index.html'

    def get(
        self, 
        request: WSGIRequest,
        *args: tuple,
        **kwargs
    ):

        users: QuerySet = CustomUser.objects.all()

        context: dict = {
            'title': 'Главная страница',
            'users': users,
        }
        return self.get_http_response(
            request,
            self.template_name,
            context,
        )


class AdminView(ViewHandler, View):

    template_name = 'proj/admin.html'

    def get(
        self, 
        request: WSGIRequest,
        *args: tuple,
        **kwargs
    ):

        context: dict = {
            "ctx_users":CustomUser.objects.all()
            }

        template_name = 'proj/admin.html'
     
        return self.get_http_response(
            request,
            self.template_name,
            context,
        )


class ShowView(ViewHandler, View):
    
    queryset: QuerySet = Homework.objects.get_not_deleted()
    
    template_name = 'proj/show.html'

    def get(
        self, 
        request: WSGIRequest,
        *args: tuple,
        **kwargs: dict
    ):
        homework_id: int = kwargs.get('homework_id', 0)
        # user: User = CustomUser.objects.get(id=user_id)

        homework: Optional[Homework] = None
        
        try:
            homework = self.queryset.filter(user=self.request.user)\
                .get(id=homework_id)
            
        except Homework.DoesNotExist:
            return self.get_http_response(
                request,
                'proj/login.html'
            )
        else:
            context: dict = {
                'ctx_title': 'Домашние задания',
                'ctx_homework': homework,
            }
        
            return self.get_http_response(
                request,
                self.template_name,
                context,
            )


class  LogoutView(ViewHandler, View):

    def get(
        self, 
        request: WSGIRequest,
        *args: tuple,
        **kwargs
    ):
        dj_logout(request)

        form: CustomUserForm = CustomUserForm(
            request.POST
        )

        context: dict = {
            'form': form,
        }

        template_name = 'proj/login.html'

        return self.get_http_response(
            request,
            template_name,
            context
        )


def delete(request: WSGIRequest, username: str) -> HttpResponse:
    
    user: User = CustomUser.objects.get(username=username)
    context: dict = {
        'ctx_title': 'Профиль',
        'ctx_user': user,
    }
    return render(
        request,
        'delete.html',
        context=context
    )


class CreateHomeworkViev(ViewHandler, View):
    """Homework Create View."""

    
    template_name: str = 'proj/homework_form.html'

    def get(
        self,
        request: WSGIRequest,
        *args: tuple,
        **kwargs: dict
    ) -> HttpResponse:
        """GET request handler."""

        response: Optional[HttpResponse] = \
            self.get_validated_response(
                request
            )

        form: CreateHomeworkForm = CreateHomeworkForm(
            request.POST
        )

        if response:
            return response

        context: dict = {
            'ctx_form': form,
        }
        return self.get_http_response(
            request,
            self.template_name,
            context
        )

    def post(
        self,
        request: WSGIRequest,
        *args: tuple,
        **kwargs: dict
    ) -> HttpResponse:
        """POST request handler."""

        form: CreateHomeworkForm = CreateHomeworkForm(
            request.POST or None,
            request.FILES or None
        )

        if not form.is_valid():
            context: dict = {
                'ctx_form': form,
            }
            return self.get_http_response(
                request,
                self.template_name,
                context
            )

        homework: CreateHomeworkForm = form.save(
            commit=False
        )
        homework.user = request.user
        homework.logo = request.FILES['logo']

        file_type: str = homework.logo.url.split('.')[-1].lower()

        if file_type not in Homework.IMAGE_TYPES:

            context: dict = {
                'ctx_form': form,
                'ctx_homework': homework,
                'error_message': 'PNG, JPG, JPEG',
            }

            return self.get_http_response(
                request,
                self.template_name,
                context
            )

        homework.save()

        context: dict = {
            'ctx_homework': homework
        }

apps/proj/templates/proj/additional.html
<h1>'Дополнительные данные'</h1>

apps/proj/templates/proj/admin.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/static/css/style.css">
    <link rel="preconnect" href="https://fonts.googleapis.com/%22%3E">
    <link rel="preconnect" href="https://fonts.gstatic.com/" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Oswald:wght@200&display=swap" rel="stylesheet">

    <title>{% block title %}{{ ctx_title }}{% endblock %}</title>
</head>
<body>
    <header></header>
    <main>
        <div class="user__list">

            {% for user in ctx_users %}
                <div class="user__info">
                    <h1>USER</h1>
                    <div class="info">
                        <span id="user_name"></span><br> 
                            Login:  <br> 
                            Role: <span id="role"></span>
                    </div>
                    <a class='edit' href="{% url 'page_show' user.id %}" role="button">Профиль</a>
                    <a class='edit' href="{% url 'page_delete' %}" role="button">Удалить</a>
                </div>
            {% endfor %}

        </div>
    </main>
    <script src="/static/js/app.js"></script>
</body>
</html>

apps/proj/templates/proj/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} {% endblock %}</title>
    <style>
        body{background-color: bisque;}
        p{font-weight:  bold; font-size: 25px; color: black;}
    </style>
</head>
<body>
    {% block content %}
    {% endblock %}
</body>
</html>

apps/proj/templates/proj/form_template.html
{% for field in ctx_form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2" for="title">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

apps/proj/templates/proj/homework_detail.html
{% extends 'proj/visitor.html' %}
{% block title %}{{ homework.title }}{% endblock %}
{% block homeworks_active %}active{% endblock %}

{% block body %}

<div class="container-fluid songs-container">
    <div class="row">
        <div class="col-sm-4 col-md-3">
            <div class="panel panel-default">
                <div class="panel-body">
                    <a href="{% url 'page_create_hw' %}">
                        {% if ctx_homework.logo %}
                            <img src="{{ homework.logo.url }}" class="img-responsive">
                        {% else %}
                            <h3>None</h3>
                        {% endif %}
                    </a>
                    <h1>{{ ctx_homework.title }} <small>{{ ctx_homework.subject }}</small></h1>
                    <h2>{{ ctx_homework.user.email }}</h2>
                </div>
            </div>
        </div>

        <div class="col-sm-8 col-md-9">
            <ul class="nav nav-pills" style="margin-bottom: 10px;">
                <li role="presentation" class="active"><a href="{% url 'page_create_hw' %}">ВСЕ</a></li>
                <li role="presentation"><a href="{% url 'page_create_hw'  %}">Загрузить новый файл</a></li>
            </ul>
            <div class="panel panel-default">
                <div class="panel-body">

                    <h3>ВСЕ файлы</h3>

                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}

                    <table class="table">
                        <thead>
                        <tr>
                            <th>Заголовок</th>
                            <th>Объект</th>
                            <th>Проверен ли</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for file in ctx_homework.file_set.all %}
                            <tr>
                                <td>{{ file.title }}</td>
                                <td>
                                    <a target="_blank" href="{{ file.obj.url }}">
                                        <button type="button" class="btn btn-success btn-xs">
                                            <span class="glyphicon glyphicon-eye-open"></span>&nbsp; Просмотр
                                        </button>
                                    </a>
                                </td>
                                <td>
                                    <a href="{% url 'page_create_hw' file.id %}" class="btn-favorite"><span class="glyphicon glyphicon-check {% if file.is_checked %}active{% endif %}"></span></a>
                                </td>
                                <td>
                                    <form action="{% url 'page_create_hw' file.id %}" method="post" style="display: inline;">
                                        {% csrf_token %}
                                        <input type="hidden" name="file_id" value="{{ file.id }}" />
                                        <button type="submit" class="btn btn-danger btn-xs">
                                            <span class="glyphicon glyphicon-remove"></span>&nbsp; Удалить
                                        </button>
                                    </form>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

apps/proj/templates/proj/homework_form.html
{% extends 'proj/visitor.html' %}
{% block title %}Логин{% endblock %}
{% block login_active %}active{% endblock %}

{% block body %}

<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>HomeWork</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="{% url 'page_create_hw'%}" method="post" enctype="multipart/form-data">

                        {% csrf_token %}
                        
                        {% include 'proj/form_template.html' %}

                        {{ form.as_p }}

                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Upload</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="panel-footer">
                    Don't have an account? <a href="{% url 'page_register' %}">Click here</a> to register.
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

apps/proj/templates/proj/index.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

                       <!--href="static/css/style.css"-->
    <!-- <link rel="stylesheet" href="static/university/css/style.css"> -->

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

<!--     <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Oswald:wght@200&display=swap" rel="stylesheet">
 -->
    <title>{% block title %}{{ ctx_title }}{% endblock %}</title>
</head>
<body>
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">

            <!-- Header -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>

            <div class="user__list">

                {% for homework in ctx_homeworks %}
                    <div class="user__info">
                        <h1>homework</h1>
                        <div class="info">
                            <span id="user_name">{{homework.title}} {{homework.subject}}</span>
                            <br> ID: {{homework.user.id}}
                            <br> Логин: {{homework.user.email}}
                            <br> Роль:
                            <span id="role">
                                {% if homework.user.is_superuser %}Admin{% else %}User{% endif %}
                            </span>
                        </div>
                        <a class="edit"   href="{% url 'page_show' homework.id %}" role="button">Профиль</a>
                        <a class="delete" href="{% url 'page_delete' %}" role="button">Удалить</a>

                    <!--<button class="edit" onclick="showProfile()">Профиль</button>
                        <button class="delete">Удалить</button>-->
                    </div>
                {% endfor %}

            </div>

            <!-- Items -->
            <div class="collapse navbar-collapse" id="topNavBar">
                <h3>sad</h3>
            </div>

        </div>
    </nav>

</body>
</html>

apps/proj/templates/proj/login.html
{% extends 'proj/visitor.html' %}
{% block title %}Логин{% endblock %}
{% block login_active %}active{% endblock %}

{% block body %}

<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Логин</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="{% url 'page_login'%}" method="post" enctype="multipart/form-data">

                        {% csrf_token %}

                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_username">
                                Username:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_username" maxlength="30" name="email" type="text">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_password">
                                Password:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_password" maxlength="30" name="password" type="password">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="panel-footer">
                    Don't have an account? <a href="{% url 'page_register' %}">Click here</a> to register.
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

apps/proj/templates/proj/page_main.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}University of Catalinaville{% endblock %}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'page_main' %}">.</a>
        </div>

        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="{% block register_active %}{% endblock %}"><a href="{% url 'page_register' %}">Регистрация</a></li>
                <li class="{% block login_active %}{% endblock %}"><a href="{% url 'page_login' %}">Логин</a></li>
            </ul>
        </div>
    </div>
</nav>
{% block body %}
{% endblock %}
</body>

</html>